sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: DPT9F3zzwn+xDpw887wGGIWGctjUYQ+o33KBAh73l25gmEcbvvIsuuAxrBCY6bCG6qhpDJ8C7pCTN+ABD1atPFOCYdMU+W26cJz3dv9kdg/DF4NoOVGO8ffTl414fL3jYpCsyN5yuZzqj+Dbdzf+JWZGX4rXPSNg3Yjfc8PKPlH0Q2doFQrSJy/m9ohWCQ5IC5n8+RLR68187gT9xtjNhPvmu5bii0WfsSHmoiiIsNX/Ir6nyRZ1ga6jVdIuZJ/Kj0cv7EC38ilwzAKePLtj/gcIAczCKxGhIJfrT57IxJdEq6EGJHae0W8qXaII2IPQdn2gmZb652Tqgx5/Cq4gbkQaCiM7OYF8l/Cj1AAZjOWOuu0bxIvfe80w/3k+tXviN+Q59zCVCVcUaO5BdWHY02T+tKTO5iYDaFwSLP9ON5m5zDB/zXgtAnoaJfYjdWKJC7eRyCNqkz1maJNedLzbHmxuWMuOlckB0GoB4MrZrkQeZsxeckmwaUkXaSV5KZp/8OsWda3u9x1siLsK3y41YSqbup+3vJFcyy0z+kuYsJMMvNhkSXD4MHJqjkfgmFotLDiuEJNmsi5k3VLZYMZ113HtFmI/8N+4TxH3iXiEjL4HAPZSVlwQzWJfuyVaYUbcbUVC0vJHRU6c4ePxvDC4hCm9V1j7h2JX1kH1jfUAAYA=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: tnUZIiUhEtua9bQjHrpamricvtw9wEtnPoaE3yCXMf0lWK7LvUkNxMxZAsYkmJiyH2BMsAxnBk5+bvAYWnamrdDB25W9mpll9qXiyRhf964gxj9mevhxxmWxx71Dvp+StzHpYxhv7TJ6M2bgKdsthGUewg2MxRVndxoFpnRxtE+HypbCTKnN8d99V2rwFEUsohPRIUlVhHUNJu9hEZLky4ySvNNUCrBDoe4++hdZzusfiBT80Typl4RzhIr9tt5jyfhtj6Qp6UplgkN3MGStR5pUdMuhu2ToSUUXFd5u2jD7t8Az53NwlCRMxfa2TjkPMOAHIZQ1RXO5WSwgT55xR9LROY0WFVWxw2gIRtAy6IDHWUBATAbU7cSAXBHmhTi10OUJkduMEjygq3R11k2uWWOh+WcIoMv4rEHrd1EyYH76YIwugz9QIWtV8djOyN/Y4QzwwSY/Ts/E7FVWp0+86zBdzqpEJKvnBWy01Gt9j/vRlWgNUCfjLN27B+uxRLp545/NObePkcnUlyAOxoBVl6GCtAuiywjajuh9pVANv0EYvMblpSqM7RSfz31SLf1PYOJcumTY6yhBykWXcBkt2AMJqaKQUZfgYRrvgXmztq7syja9lzsrA8GriE2w8yObKiGOAKrAOr9XdlEq1esIRxjsVMp/v8R2ukAjuH7Zsac=
